#!/usr/bin/env python3
"""
Log Analysis Tool for PathSolver User Action Logs

This script provides various analysis capabilities for the user action logs
generated by the PathSolver application.
"""

import json
import argparse
from pathlib import Path
from datetime import datetime
from collections import defaultdict, Counter
from typing import List, Dict, Any
import pandas as pd


def load_logs(log_file: Path) -> List[Dict[str, Any]]:
    """Load logs from a JSONL file."""
    events = []
    with open(log_file, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                events.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return events


def get_session_summary(events: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Generate a summary of the session."""
    if not events:
        return {}

    session_start = None
    session_end = None
    session_id = events[0].get('session_id', 'unknown')

    for event in events:
        if event['event_type'] == 'session_start':
            session_start = datetime.fromisoformat(event['timestamp'])
        elif event['event_type'] == 'session_end':
            session_end = datetime.fromisoformat(event['timestamp'])

    if not session_end and events:
        session_end = datetime.fromisoformat(events[-1]['timestamp'])

    duration = (session_end - session_start).total_seconds() if session_start and session_end else 0

    event_counts = Counter(event['event_type'] for event in events)

    return {
        'session_id': session_id,
        'start_time': session_start.isoformat() if session_start else None,
        'end_time': session_end.isoformat() if session_end else None,
        'duration_seconds': duration,
        'duration_minutes': duration / 60,
        'total_events': len(events),
        'event_counts': dict(event_counts)
    }


def analyze_algorithm_usage(events: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Analyze how users interact with the algorithm."""
    algo_events = [e for e in events if 'algorithm' in e['event_type']]

    if not algo_events:
        return {}

    starts = [e for e in algo_events if e['event_type'] == 'algorithm_start']
    completes = [e for e in algo_events if e['event_type'] == 'algorithm_complete']
    steps = [e for e in algo_events if e['event_type'] == 'algorithm_step']
    back_steps = [e for e in algo_events if e['event_type'] == 'algorithm_back_step']

    # Calculate average steps per run
    step_counts = []
    current_steps = 0
    for event in algo_events:
        if event['event_type'] == 'algorithm_start':
            current_steps = 0
        elif event['event_type'] == 'algorithm_step':
            current_steps += 1
        elif event['event_type'] == 'algorithm_complete':
            step_counts.append(current_steps)

    # Graph types used
    graph_types = [e['data'].get('graph_type') for e in starts if 'graph_type' in e['data']]

    return {
        'algorithm_runs': len(starts),
        'completed_runs': len(completes),
        'completion_rate': len(completes) / len(starts) if starts else 0,
        'total_steps': len(steps),
        'back_steps': len(back_steps),
        'avg_steps_per_run': sum(step_counts) / len(step_counts) if step_counts else 0,
        'graph_types_used': Counter(graph_types)
    }


def analyze_graph_interactions(events: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Analyze graph manipulation behaviors."""
    graph_events = [e for e in events if any(x in e['event_type'] for x in ['node', 'edge', 'graph_selected'])]

    node_additions = len([e for e in graph_events if e['event_type'] == 'node_added'])
    node_deletions = len([e for e in graph_events if e['event_type'] == 'node_deleted'])
    edge_additions = len([e for e in graph_events if e['event_type'] == 'edge_added'])
    edge_deletions = len([e for e in graph_events if e['event_type'] == 'edge_deleted'])
    edge_updates = len([e for e in graph_events if e['event_type'] == 'edge_weight_updated'])

    graph_selections = [e for e in events if e['event_type'] == 'graph_selected']
    selected_graphs = Counter(e['data'].get('graph_type') for e in graph_selections)

    return {
        'total_graph_modifications': len(graph_events),
        'nodes_added': node_additions,
        'nodes_deleted': node_deletions,
        'edges_added': edge_additions,
        'edges_deleted': edge_deletions,
        'edge_weights_updated': edge_updates,
        'graphs_selected': dict(selected_graphs),
        'custom_graph_usage': node_additions > 0 or edge_additions > 0
    }


def analyze_game_performance(events: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Analyze prediction game performance."""
    predictions = [e for e in events if e['event_type'] == 'prediction_made']

    if not predictions:
        return {'game_used': False}

    correct = sum(1 for p in predictions if p['data'].get('is_correct', False))
    total = len(predictions)
    accuracy = correct / total if total > 0 else 0

    scores = [p['data'].get('score', 0) for p in predictions]
    max_score = max(scores) if scores else 0

    consecutive = [p['data'].get('consecutive_correct', 0) for p in predictions]
    max_streak = max(consecutive) if consecutive else 0

    return {
        'game_used': True,
        'total_predictions': total,
        'correct_predictions': correct,
        'accuracy': accuracy,
        'max_score': max_score,
        'max_streak': max_streak
    }


def analyze_quiz_performance(events: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Analyze solution quiz performance."""
    quiz_events = [e for e in events if e['event_type'] == 'quiz_submitted']

    if not quiz_events:
        return {'quiz_used': False}

    correct = sum(1 for q in quiz_events if q['data'].get('is_correct', False))
    total = len(quiz_events)

    return {
        'quiz_used': True,
        'total_submissions': total,
        'correct_submissions': correct,
        'accuracy': correct / total if total > 0 else 0
    }


def analyze_settings_changes(events: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Analyze settings changes."""
    settings_events = [e for e in events if any(x in e['event_type'] for x in
                                                ['language', 'font_size', 'difficulty', 'settings_unlocked'])]

    language_changes = [e for e in settings_events if e['event_type'] == 'language_changed']
    font_changes = [e for e in settings_events if e['event_type'] == 'font_size_changed']
    difficulty_changes = [e for e in settings_events if e['event_type'] == 'difficulty_changed']

    return {
        'total_settings_changes': len(settings_events),
        'language_changes': len(language_changes),
        'font_size_changes': len(font_changes),
        'difficulty_changes': len(difficulty_changes)
    }


def export_to_csv(events: List[Dict[str, Any]], output_file: Path):
    """Export events to CSV format."""
    # Flatten the nested data structure
    flattened = []
    for event in events:
        row = {
            'timestamp': event['timestamp'],
            'session_id': event['session_id'],
            'event_type': event['event_type']
        }
        # Add data fields with prefix
        for key, value in event.get('data', {}).items():
            if isinstance(value, (dict, list)):
                row[f'data_{key}'] = json.dumps(value)
            else:
                row[f'data_{key}'] = value
        flattened.append(row)

    df = pd.DataFrame(flattened)
    df.to_csv(output_file, index=False)
    print(f"Exported {len(events)} events to {output_file}")


def print_report(log_file: Path):
    """Print a comprehensive report of the log file."""
    events = load_logs(log_file)

    if not events:
        print(f"No events found in {log_file}")
        return

    print(f"\n{'='*60}")
    print(f"PathSolver User Action Log Analysis")
    print(f"{'='*60}\n")

    print(f"Log file: {log_file}")
    print(f"Total events: {len(events)}\n")

    # Session Summary
    print("SESSION SUMMARY")
    print("-" * 60)
    summary = get_session_summary(events)
    print(f"Session ID: {summary.get('session_id')}")
    print(f"Start time: {summary.get('start_time')}")
    print(f"End time: {summary.get('end_time')}")
    print(f"Duration: {summary.get('duration_minutes', 0):.2f} minutes")
    print(f"Total events: {summary.get('total_events', 0)}\n")

    print("Event breakdown:")
    for event_type, count in sorted(summary.get('event_counts', {}).items()):
        print(f"  {event_type}: {count}")
    print()

    # Algorithm Usage
    print("ALGORITHM USAGE")
    print("-" * 60)
    algo_stats = analyze_algorithm_usage(events)
    if algo_stats:
        print(f"Algorithm runs: {algo_stats.get('algorithm_runs', 0)}")
        print(f"Completed runs: {algo_stats.get('completed_runs', 0)}")
        print(f"Completion rate: {algo_stats.get('completion_rate', 0):.1%}")
        print(f"Total steps: {algo_stats.get('total_steps', 0)}")
        print(f"Back steps: {algo_stats.get('back_steps', 0)}")
        print(f"Avg steps per run: {algo_stats.get('avg_steps_per_run', 0):.1f}")
        print(f"Graph types used: {dict(algo_stats.get('graph_types_used', {}))}")
    else:
        print("No algorithm usage recorded")
    print()

    # Graph Interactions
    print("GRAPH INTERACTIONS")
    print("-" * 60)
    graph_stats = analyze_graph_interactions(events)
    print(f"Total modifications: {graph_stats.get('total_graph_modifications', 0)}")
    print(f"Nodes added: {graph_stats.get('nodes_added', 0)}")
    print(f"Nodes deleted: {graph_stats.get('nodes_deleted', 0)}")
    print(f"Edges added: {graph_stats.get('edges_added', 0)}")
    print(f"Edges deleted: {graph_stats.get('edges_deleted', 0)}")
    print(f"Edge weights updated: {graph_stats.get('edge_weights_updated', 0)}")
    print(f"Custom graph usage: {graph_stats.get('custom_graph_usage', False)}")
    print(f"Graphs selected: {graph_stats.get('graphs_selected', {})}")
    print()

    # Game Performance
    print("PREDICTION GAME PERFORMANCE")
    print("-" * 60)
    game_stats = analyze_game_performance(events)
    if game_stats.get('game_used'):
        print(f"Total predictions: {game_stats.get('total_predictions', 0)}")
        print(f"Correct predictions: {game_stats.get('correct_predictions', 0)}")
        print(f"Accuracy: {game_stats.get('accuracy', 0):.1%}")
        print(f"Max score: {game_stats.get('max_score', 0)}")
        print(f"Max streak: {game_stats.get('max_streak', 0)}")
    else:
        print("Prediction game not used")
    print()

    # Quiz Performance
    print("SOLUTION QUIZ PERFORMANCE")
    print("-" * 60)
    quiz_stats = analyze_quiz_performance(events)
    if quiz_stats.get('quiz_used'):
        print(f"Total submissions: {quiz_stats.get('total_submissions', 0)}")
        print(f"Correct submissions: {quiz_stats.get('correct_submissions', 0)}")
        print(f"Accuracy: {quiz_stats.get('accuracy', 0):.1%}")
    else:
        print("Solution quiz not used")
    print()

    # Settings Changes
    print("SETTINGS CHANGES")
    print("-" * 60)
    settings_stats = analyze_settings_changes(events)
    print(f"Total changes: {settings_stats.get('total_settings_changes', 0)}")
    print(f"Language changes: {settings_stats.get('language_changes', 0)}")
    print(f"Font size changes: {settings_stats.get('font_size_changes', 0)}")
    print(f"Difficulty changes: {settings_stats.get('difficulty_changes', 0)}")
    print()


def main():
    parser = argparse.ArgumentParser(description='Analyze PathSolver user action logs')
    parser.add_argument('log_file', type=Path, help='Path to the log file (JSONL format)')
    parser.add_argument('--export-csv', type=Path, help='Export events to CSV file')
    parser.add_argument('--summary-only', action='store_true', help='Show only session summary')

    args = parser.parse_args()

    if not args.log_file.exists():
        print(f"Error: Log file not found: {args.log_file}")
        return

    if args.export_csv:
        events = load_logs(args.log_file)
        export_to_csv(events, args.export_csv)
    elif args.summary_only:
        events = load_logs(args.log_file)
        summary = get_session_summary(events)
        print(json.dumps(summary, indent=2))
    else:
        print_report(args.log_file)


if __name__ == '__main__':
    main()
